### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [EmmanuelOmoiya/CRUL#1]
Hey!

I suggest adding badges for tech stack for a cool look

If its ok, I would like to work on this issue

Thoughts?? (example)
![badges](https://user-images.githubusercontent.com/121221252/220325482-f6f28216-55a8-4e57-908c-0a17cf2ff448.png)

**Comment by EmmanuelOmoiya** [comment]
Yh, this would be nice.
I'll assign this to you real quick.

**Comment by the-amazing-atharva** [comment]
Thanks for the reply
Working on it in some time
